#ifndef RELEASE_IDENTITY_H
#define RELEASE_IDENTITY_H

/* Generated by tools/build_catalog_release.py from the published catalog. */
#define FW_RELEASE_ID "mspm0g3507.lua-modular"
#define FW_RELEASE_VERSION "1.0.6"
#define FW_RELEASE_TARGET "MSPM0G3507"
#define FW_RELEASE_CATALOG_SHA256 \
    "f3fda414878caf2a808b9feb689b4829e3ef3202e83f93975b60c502b3cb3cba"
#define FW_RELEASE_NMUP_FORMAT 1u

#endif
