#!/usr/bin/env python3
"""Create the immutable modular catalog identity and top-level release manifest."""

import argparse
import hashlib
import json
from pathlib import Path


WORKSPACE = Path(__file__).resolve().parents[1]
ROOT = WORKSPACE / "mspm0_lua"
MODULES = ROOT / "modules" / "modules.json"
INDEX = ROOT / "build_modules" / "index.json"
CORE = ROOT / "build_modular" / "mspm0_lua_modular.bin"
API = ROOT / "release" / "mspm0-lua.api.json"
IDENTITY_HEADER = ROOT / "app" / "release_identity.h"
RELEASE_MANIFEST = ROOT / "release" / "catalog_manifest.json"
RELEASE_DOCS = {
    "IDE_RELEASE_CONTRACT.md": ROOT / "docs" / "IDE_RELEASE_CONTRACT.md",
    "HOST_INTEGRATION.md": ROOT / "docs" / "HOST_INTEGRATION.md",
    "NATIVE_MODULES.md": ROOT / "docs" / "NATIVE_MODULES.md",
}


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def load_json(path):
    return json.loads(path.read_text(encoding="utf-8"))


def catalog_records():
    modules = load_json(MODULES)
    index = load_json(INDEX)
    if index.get("catalog") != modules.get("catalog"):
        raise SystemExit("index catalog identity differs from modules.json")
    if index.get("modules_definition_sha256") != sha256(MODULES.read_bytes()):
        raise SystemExit("index was built for a different modules.json")
    paths = [MODULES, INDEX]
    for name in sorted(index.get("modules", {})):
        variants = index["modules"][name].get("variants", [])
        if len(variants) != int(modules["layout"]["slot_count"]):
            raise SystemExit(f"module {name} does not have a complete variant set")
        for variant in sorted(variants, key=lambda value: int(value["slot"])):
            path = (ROOT / variant["image"]).resolve()
            try:
                path.relative_to((ROOT / "build_modules").resolve())
            except ValueError as error:
                raise SystemExit(f"catalog path escapes build_modules: {path}") from error
            if not path.is_file():
                raise SystemExit(f"missing catalog artifact: {path}")
            data = path.read_bytes()
            if (len(data) != int(variant["size"]) or
                    sha256(data) != variant["sha256"]):
                raise SystemExit(f"catalog artifact mismatch: {path}")
            paths.append(path)
    records = []
    for path in sorted(set(paths), key=lambda value: value.relative_to(ROOT).as_posix()):
        data = path.read_bytes()
        relative = path.relative_to(ROOT).as_posix()
        digest = sha256(data)
        encoded = f"{relative}\0{len(data)}\0{digest}\n".encode("utf-8")
        records.append({
            "path": relative,
            "length": len(data),
            "sha256": digest,
            "canonical_record": encoded,
        })
    return modules, index, records


def catalog_sha256(records):
    digest = hashlib.sha256()
    for record in records:
        digest.update(record["canonical_record"])
    return digest.hexdigest()


def write_identity_header(identity, catalog_hash):
    text = f'''#ifndef RELEASE_IDENTITY_H
#define RELEASE_IDENTITY_H

/* Generated by tools/build_catalog_release.py from the published catalog. */
#define FW_RELEASE_ID "{identity['firmware_id']}"
#define FW_RELEASE_VERSION "{identity['firmware_version']}"
#define FW_RELEASE_TARGET "{identity['target']}"
#define FW_RELEASE_CATALOG_SHA256 \\
    "{catalog_hash}"
#define FW_RELEASE_NMUP_FORMAT {int(identity['nmup_format'])}u

#endif
'''
    if not IDENTITY_HEADER.exists() or IDENTITY_HEADER.read_text(encoding="ascii") != text:
        IDENTITY_HEADER.write_text(text, encoding="ascii", newline="\n")


def public_record(record):
    return {key: record[key] for key in ("path", "length", "sha256")}


def publish_docs():
    output = ROOT / "release" / "docs"
    output.mkdir(parents=True, exist_ok=True)
    for name, source in RELEASE_DOCS.items():
        if not source.is_file():
            raise SystemExit(f"missing release documentation: {source}")
        (output / name).write_bytes(source.read_bytes())


def finalize(modules, index, records, catalog_hash):
    if not CORE.is_file():
        raise SystemExit(f"missing modular core: {CORE}")
    if not API.is_file():
        raise SystemExit(f"missing complete API metadata: {API}")
    identity = modules["catalog"]
    publish_docs()
    manifest = {
        "schema": 1,
        "firmware_id": identity["firmware_id"],
        "firmware_version": identity["firmware_version"],
        "target": identity["target"],
        "core_abi": identity["core_abi"],
        "module_format": identity["module_format"],
        "nmup_format": identity["nmup_format"],
        "layout": modules["layout"],
        "artifacts": {
            "core": {
                "path": CORE.relative_to(ROOT).as_posix(),
                "length": CORE.stat().st_size,
                "sha256": sha256(CORE.read_bytes()),
            },
            "modules": {
                "path": MODULES.relative_to(ROOT).as_posix(),
                "length": MODULES.stat().st_size,
                "sha256": sha256(MODULES.read_bytes()),
            },
            "index": {
                "path": INDEX.relative_to(ROOT).as_posix(),
                "length": INDEX.stat().st_size,
                "sha256": sha256(INDEX.read_bytes()),
            },
            "api": {
                "path": API.relative_to(ROOT).as_posix(),
                "length": API.stat().st_size,
                "sha256": sha256(API.read_bytes()),
            },
        },
        "catalog_sha256": catalog_hash,
        "catalog_hash_algorithm": {
            "name": "sha256-path-length-content-v1",
            "ordering": "ascending UTF-8 relative POSIX path bytes",
            "record": "utf8(path) || NUL || ascii(decimal_length) || NUL || lowercase_sha256 || LF",
            "digest": "SHA-256 of the concatenated records",
            "file_count": len(records),
        },
        "catalog_files": [public_record(record) for record in records],
    }
    RELEASE_MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    RELEASE_MANIFEST.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print("manifest", RELEASE_MANIFEST)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--prepare-only", action="store_true")
    args = parser.parse_args()
    modules, index, records = catalog_records()
    catalog_hash = catalog_sha256(records)
    write_identity_header(modules["catalog"], catalog_hash)
    print(f"CATALOG_SHA256 {catalog_hash} files={len(records)}")
    if not args.prepare_only:
        finalize(modules, index, records, catalog_hash)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
