#!/usr/bin/env python3
"""Generate compact 64-pin MSPM0G3507 peripheral route tables from TI headers."""

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEVICE = ROOT / "mspm0_lua/third_party/mspm0_sdk/source/ti/devices/msp/m0p/mspm0g350x.h"
OUT_H = ROOT / "mspm0_lua/modules/g3507_pin_routes.h"
OUT_JSON = ROOT / "mspm0_lua/docs/MSPM0G3507_64PIN_CAPABILITIES.json"
OUT_MD = ROOT / "mspm0_lua/docs/MSPM0G3507_64PIN_CAPABILITIES.md"

PINCM = {
    **{f"PA{i}": v for i, v in enumerate([
        0, 1, 6, 7, 8, 9, 10, 13, 18, 19, 20, 21, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 45, 46, 52, 53, 54, 58, 59, 2, 3, 4, 5,
    ])},
    **{f"PB{i}": v for i, v in enumerate([
        11, 12, 14, 15, 16, 17, 22, 23, 24, 25, 26, 27, 28, 29,
        30, 31, 32, 42, 43, 44, 47, 48, 49, 50, 51, 55, 56, 57,
    ])},
}

ADC_ROUTES = [
    ("PA27", 0, 0), ("PA26", 0, 1), ("PA25", 0, 2),
    ("PA24", 0, 3), ("PB25", 0, 4), ("PB24", 0, 5),
    ("PB20", 0, 6), ("PA22", 0, 7), ("PA14", 0, 12),
    ("PA15", 1, 0), ("PA16", 1, 1), ("PA17", 1, 2),
    ("PA18", 1, 3), ("PB17", 1, 4), ("PB18", 1, 5),
    ("PB19", 1, 6), ("PA21", 1, 7),
]

DEFINE_RE = re.compile(
    r"^#define IOMUX_PINCM(\d+)_PF_([A-Z0-9_]+)\s+"
    r"\(\(uint32_t\)0X([0-9A-F]+)\)", re.MULTILINE
)


def c_rows(name, rows):
    body = "\n".join("    {" + ", ".join(map(str, row)) + "}," for row in rows)
    return f"static const g3507_route_t {name}[] = {{\n{body}\n}};\n"


def c_timer_rows(rows):
    values = []
    for iomux, pf, instance, role in rows:
        encoded = (iomux | (pf << 6) | (instance << 10) |
                   ((role & 3) << 13) | ((role & 0x80) << 8))
        values.append(f"    0x{encoded:04X}u,")
    return "static const uint16_t g3507_timer_routes[] = {\n" + \
        "\n".join(values) + "\n};\n"


def main():
    text = DEVICE.read_text(encoding="utf-8")
    by_iomux = {value: pin for pin, value in PINCM.items()}
    pins = {pin: [] for pin in PINCM}
    i2c, spi, uart, timer, can = [], [], [], [], []
    spi_roles = {
        "SCLK": 0, "PICO": 1, "POCI": 2, "CS0": 3,
        "CS1_POCI1": 4, "CS2_POCI2": 5, "CS3_CD_POCI3": 6,
    }
    uart_roles = {"TX": 0, "RX": 1, "CTS": 2, "RTS": 3}
    timer_ids = {"TIMA0": 0, "TIMA1": 1, "TIMG0": 2,
                 "TIMG6": 3, "TIMG7": 4, "TIMG8": 5, "TIMG12": 6}

    for match in DEFINE_RE.finditer(text):
        iomux = int(match.group(1)) - 1
        signal = match.group(2)
        pf = int(match.group(3), 16)
        pin = by_iomux.get(iomux)
        if pin is None or signal == "UNCONNECTED" or signal.startswith("GPIO"):
            continue
        pins[pin].append({"pf": pf, "signal": signal})

        m = re.fullmatch(r"I2C([01])_(SCL|SDA)", signal)
        if m:
            i2c.append((iomux, pf, int(m.group(1)), 0 if m.group(2) == "SCL" else 1))
            continue
        m = re.fullmatch(r"SPI([01])_(SCLK|PICO|POCI|CS0|CS1_POCI1|CS2_POCI2|CS3_CD_POCI3)", signal)
        if m:
            spi.append((iomux, pf, int(m.group(1)), spi_roles[m.group(2)]))
            continue
        m = re.fullmatch(r"UART([0-3])_(TX|RX|CTS|RTS)", signal)
        if m:
            uart.append((iomux, pf, int(m.group(1)), uart_roles[m.group(2)]))
            continue
        m = re.fullmatch(r"(TIMA[01]|TIMG(?:0|6|7|8|12))_CCP([0-3])(_CMPL)?", signal)
        if m:
            role = int(m.group(2)) | (0x80 if m.group(3) else 0)
            timer.append((iomux, pf, timer_ids[m.group(1)], role))
            continue
        # IDX and fault inputs remain in the generated capability document via
        # pins[]. They are not CCP routes and must not enter the runtime table.
        if re.fullmatch(r"TIMG8_IDX|TIMA_FAULT[0-2]", signal):
            continue
        m = re.fullmatch(r"CANFD0_CAN(TX|RX)", signal)
        if m:
            can.append((iomux, pf, 0, 0 if m.group(1) == "TX" else 1))

    adc = [(PINCM[pin], 0, instance, channel)
           for pin, instance, channel in ADC_ROUTES]
    tables = {"i2c": i2c, "spi": spi, "uart": uart,
              "timer": timer, "can": can, "adc": adc}
    for rows in tables.values():
        rows.sort()

    header = """#ifndef G3507_PIN_ROUTES_H
#define G3507_PIN_ROUTES_H

#include <stdint.h>

/* Generated by tools/gen_g3507_pin_routes.py from TI mspm0g350x.h.
 * iomux is the zero-based PINCM index; role is peripheral-specific. */
typedef struct {
    uint8_t iomux;
    uint8_t pf;
    uint8_t instance;
    uint8_t role;
} g3507_route_t;

enum { G3507_I2C_SCL = 0, G3507_I2C_SDA = 1 };
enum { G3507_SPI_SCLK = 0, G3507_SPI_PICO = 1, G3507_SPI_POCI = 2,
       G3507_SPI_CS0 = 3, G3507_SPI_CS1_POCI1 = 4,
       G3507_SPI_CS2_POCI2 = 5, G3507_SPI_CS3_POCI3 = 6 };
enum { G3507_UART_TX = 0, G3507_UART_RX = 1,
       G3507_UART_CTS = 2, G3507_UART_RTS = 3 };
enum { G3507_TIMER_TIMA0 = 0, G3507_TIMER_TIMA1 = 1,
       G3507_TIMER_TIMG0 = 2, G3507_TIMER_TIMG6 = 3,
       G3507_TIMER_TIMG7 = 4, G3507_TIMER_TIMG8 = 5,
       G3507_TIMER_TIMG12 = 6 };
enum { G3507_CAN_TX = 0, G3507_CAN_RX = 1 };

#define G3507_TIMER_ROUTE_IOMUX(v) ((unsigned)(v) & 0x3fu)
#define G3507_TIMER_ROUTE_PF(v)    (((unsigned)(v) >> 6u) & 0x0fu)
#define G3507_TIMER_ROUTE_INST(v)  (((unsigned)(v) >> 10u) & 0x07u)
#define G3507_TIMER_ROUTE_CH(v)    (((unsigned)(v) >> 13u) & 0x03u)
#define G3507_TIMER_ROUTE_CMPL(v)  (((unsigned)(v) >> 15u) & 0x01u)

"""
    for name, rows in tables.items():
        header += (c_timer_rows(rows) if name == "timer" else
                   c_rows(f"g3507_{name}_routes", rows)) + "\n"
    header += "#endif\n"
    OUT_H.write_text(header, encoding="ascii")

    payload = {
        "device": "MSPM0G3507",
        "package": "PM LQFP-64",
        "gpio_count": 60,
        "pins": {pin: {"iomux": PINCM[pin], "functions": pins[pin]}
                 for pin in PINCM},
        "adc_routes": [
            {"pin": pin, "instance": instance, "channel": channel}
            for pin, instance, channel in ADC_ROUTES
        ],
        "route_counts": {name: len(rows) for name, rows in tables.items()},
    }
    OUT_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# MSPM0G3507 64-pin capability map", "",
        "Generated from TI `mspm0g350x.h` for the PM LQFP-64 package.", "",
        "| Peripheral | Routes |", "|---|---:|",
    ]
    lines += [f"| {name.upper()} | {len(rows)} |" for name, rows in tables.items()]
    lines += ["", "| Pin | PINCM | Digital functions |", "|---|---:|---|"]
    for pin, iomux in PINCM.items():
        functions = ", ".join(f"{item['signal']}[PF{item['pf']}]" for item in pins[pin])
        analog = [f"ADC{instance}_A{channel}" for p, instance, channel in ADC_ROUTES if p == pin]
        if analog:
            functions = ", ".join(analog + ([functions] if functions else []))
        lines.append(f"| {pin} | {iomux + 1} | {functions} |")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {OUT_H}")
    print(f"generated {OUT_JSON}")
    print(f"generated {OUT_MD}")
    print("route counts", {name: len(rows) for name, rows in tables.items()})


if __name__ == "__main__":
    main()
